language: node_js
node_js:
- stable
install: npm install
script:
- npm test
- npm run ci
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_b10a2b124130_key -iv $encrypted_b10a2b124130_iv
  -in domain-key.pem.enc -out sslcert/domain-key.pem -d
