language: node_js
# 
node_js:
- stable

before_install:
  - npm i -g npm

install: npm install && npm install cypress

script:
- npm test
- npm run ci

cache:
  directories:
  - node_modules
  - ~/.cache
before_install:
- openssl aes-256-cbc -K $encrypted_579533767fd6_key -iv $encrypted_579533767fd6_iv
  -in domain-key.pem.enc -out sslcert/domain-key.pem -d

after_success:
- openode ci-conf $OPENODE_TOKEN isas.zlepsi.me
- openode deploy